---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
Require::Require("pkgdown")
Require::Require("devtools")
load_all(".")
# source("R/asis.R") # this is not needed because of previous line
options('reproducible.cachePath' = "cache")
build_site(new_process = FALSE)
lapply(dir("docs/exercises", full.names = TRUE, pattern = "\\.Rmd$"), function(file)
  rmarkdown::render(file, rmarkdown::html_document(toc = TRUE)))

# lapply(dir("docs/SpaDESInAction2", full.names = TRUE, pattern = "\\.Rmd$"), function(file)
#   rmarkdown::render(file, rmarkdown::html_document(toc = TRUE)))

replaceRemoteLinksInArticles(replacementList, c("", "articles"))
replaceRemoteLinksMultiline(replacementStarts, replacementEnds, c("", "articles", "articlesJan2020", "articlesFeb2018", "articlesMay2018", "articlesSept2018", "articlesOct2019"))
```

For local only
```{r}
Require::Require("pkgdown")
devtools::load_all(".")
options('reproducible.cachePath' = "cache")
build_site(new_process = FALSE)
replaceRemoteLinksInArticles(replacementList, c("", "articles"))
```
