---
title       : "Exercises: Sharing Modules and Data"
author      : "Alex M Chubaty & Eliot McIntire"
date        : "October 2019"
output: 
  html_document: 
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = TRUE, eval = FALSE)
```

# Install the `SpaDES.shiny` package

```{r install}
devtools::install_github("PredictiveEcology/SpaDES.shiny@development")

library(SpaDES.shiny)
```


# `shine`

1. Explore the `LCC2005` (or your working parent module) using the `shine` function:

    ```{r shine}
    ## hint: the lcc simulation was created in exercise 07-module-integration
    shine(lcc05)
    ```

# Sharing your module and data with others

Before you can add your newly created module to a `SpaDES` module repository, you must ensure it is complete!

1. Review the [module development checklist](https://github.com/PredictiveEcology/SpaDES/wiki/Getting-Started-Guide#module-development-checklist), and update your parent module and all children accordingly.
